export const student = [
  {
    id: '1',
    name: 'Jamil',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly and maintenance',
  },
  {
    id: '2',
    name: 'Tarek',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly and maintenance',
  },
  {
    id: '3',
    name: 'Luqman',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly and maintenance',
  },
  {
    id: '4',
    name: 'Razan',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly and maintenance',
  },
  {
    id: '5',
    name: 'Ramzi',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly and maintenance',
  },
  {
    id: '6',
    name: 'Kareem',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly and maintenance',
  },
  {
    id: '7',
    name: 'Yahya',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly and maintenance',
  },
  {
    id: '8',
    name: 'Sufyan',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly and maintenance',
  },
  {
    id: '9',
    name: 'Ibrahim',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly and maintenance',
  },
  {
    id: '10',
    name: 'Rand',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly and maintenance',
  },
  {
    id: '11',
    name: 'Abrar',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly and maintenance',
  },
  {
    id: '12',
    name: 'Heba',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly and maintenance',
  },
  {
    id: '13',
    name: 'Firas',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly and maintenance',
  },
  {
    id: '14',
    name: 'Samar',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly and maintenance',
  },
  {
    id: '15',
    name: 'Saleh',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly and maintenance',
  },
  {
    id: '16',
    name: 'Louay',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly and maintenance',
  },
  {
    id: '17',
    name: 'Munir',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly and maintenance',
  },
  {
    id: '18',
    name: 'Hana',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'business',
  },
  {
    id: '19',
    name: 'Nawaf',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'business',
  },
  {
    id: '20',
    name: 'Yasmine',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'business',
  },
  {
    id: '21',
    name: 'Walid',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'business',
  },
  {
    id: '22',
    name: 'Majid',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'business',
  },
  {
    id: '23',
    name: 'Hani',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'business',
  },
  {
    id: '24',
    name: 'Osama',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'business',
  },
  {
    id: '25',
    name: 'Haider',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'business',
  },
  {
    id: '26',
    name: 'Zuhair',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'computer assembly and maintenance',
  },
  {
    id: '27',
    name: 'Mazin',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'computer assembly and maintenance',
  },
  {
    id: '28',
    name: 'Eman',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'computer assembly and maintenance',
  },
  {
    id: '29',
    name: 'Yusuf',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'computer assembly and maintenance',
  },
  {
    id: '30',
    name: 'Ziad',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'computer assembly and maintenance',
  },
  {
    id: '31',
    name: 'Kamal',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'computer assembly and maintenance',
  },
  {
    id: '32',
    name: 'Amr',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'computer assembly and maintenance',
  },
  {
    id: '33',
    name: 'Hamza',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'computer assembly and maintenance',
  },
  {
    id: '34',
    name: 'Fadel',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'computer assembly and maintenance',
  },
  {
    id: '35',
    name: 'Aisha',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'computer assembly and maintenance',
  },
  {
    id: '36',
    name: 'Sara',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'computer assembly and maintenance',
  },
  {
    id: '37',
    name: 'Salim',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'business',
  },
  {
    id: '38',
    name: 'Zaki',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'business',
  },
  {
    id: '39',
    name: 'Abdullah',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'business',
  },
  {
    id: '40',
    name: 'Dina',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'business',
  },
  {
    id: '41',
    name: 'Hussein',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'business',
  },
  {
    id: '42',
    name: 'Ghassan',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'business',
  },
  {
    id: '43',
    name: 'Ghada',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '44',
    name: 'Diyaa',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '45',
    name: 'Ahmed',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '46',
    name: 'Taim',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '47',
    name: 'Tariq',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '48',
    name: 'Suha',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '49',
    name: 'Khalid',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '50',
    name: 'Anas',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '51',
    name: 'Fatima',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '52',
    name: 'Raed',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '53',
    name: 'Mahmoud',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '54',
    name: 'Manar',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '55',
    name: 'Mariam',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '56',
    name: 'Widad',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '57',
    name: 'Roaa',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '58',
    name: 'Sana',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '59',
    name: 'Obada',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '60',
    name: 'Adnan',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '61',
    name: 'Rami',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '62',
    name: 'Mohammed',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '63',
    name: 'Mousa',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '64',
    name: 'Baraa',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '65',
    name: 'Bilal',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '66',
    name: 'Adel',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '67',
    name: 'Ihab',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '68',
    name: 'Louai',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '69',
    name: 'Ghaith',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
  },
  {
    id: '70',
    name: 'Reem',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '71',
    name: 'Saad',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '72',
    name: 'Jawad',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '73',
    name: 'Mostafa',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '74',
    name: 'Nadia',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '75',
    name: 'Essam',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '76',
    name: 'Lina',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '77',
    name: 'Rania',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '78',
    name: 'Tamara',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '79',
    name: 'Ali',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '80',
    name: 'Qasim',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '81',
    name: 'Naeem',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '82',
    name: 'Aws',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '83',
    name: 'Layla',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '84',
    name: 'Hassan',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '85',
    name: 'Omar',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '86',
    name: 'Nasser',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '87',
    name: 'Nour',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '88',
    name: 'Faisal',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '89',
    name: 'Issam',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '90',
    name: 'Waseem',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '91',
    name: 'Mustafa',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '92',
    name: 'Bassam',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '93',
    name: 'Wael',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '94',
    name: 'Mona',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '95',
    name: 'Shahed',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '96',
    name: 'Sami',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '97',
    name: 'Marwan',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '98',
    name: 'Badr',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
  {
    id: '99',
    name: 'Rafiq',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly and maintenance',
  },
];
