export const student = [
  {
    id: '1',
    name: 'Jamil Naji Nasrallah',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly',
    studentCode: '11816',
  },
  {
    id: '2',
    name: 'Tarek Bassel Awad',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly',
    studentCode: '12309',
  },
  {
    id: '3',
    name: 'Luqman Fouad Rahal',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly',
    studentCode: '13345',
  },
  {
    id: '4',
    name: 'Razan Amjad Suleiman',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly',
    studentCode: '14798',
  },
  {
    id: '5',
    name: 'Ramzi Jamal Hassan',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly',
    studentCode: '15340',
  },
  {
    id: '6',
    name: 'Kareem Wadih Zahran',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly',
    studentCode: '16195',
  },
  {
    id: '7',
    name: 'Yahya Fares Zaidan',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly',
    studentCode: '17103',
  },
  {
    id: '8',
    name: 'Sufyan Anwar Zaidan',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly',
    studentCode: '18308',
  },
  {
    id: '9',
    name: 'Ibrahim Fouad Karim',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly',
    studentCode: '19843',
  },
  {
    id: '10',
    name: 'Rand Sami Suleiman',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly',
    studentCode: '110463',
  },
  {
    id: '11',
    name: 'Abrar Sami Nasrallah',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly',
    studentCode: '111807',
  },
  {
    id: '12',
    name: 'Heba Karim Jaber',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly',
    studentCode: '112329',
  },
  {
    id: '13',
    name: 'Firas Amjad Suleiman',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly',
    studentCode: '113842',
  },
  {
    id: '14',
    name: 'Samar Zahir Nasser',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly',
    studentCode: '114571',
  },
  {
    id: '15',
    name: 'Saleh Talal Yousef',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly',
    studentCode: '115428',
  },
  {
    id: '16',
    name: 'Louay Nabil Najjar',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly',
    studentCode: '116636',
  },
  {
    id: '17',
    name: 'Munir Riyad Rasheed',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'computer assembly',
    studentCode: '117418',
  },
  {
    id: '18',
    name: 'Hana Fouad Yousef',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'business',
    studentCode: '118444',
  },
  {
    id: '19',
    name: 'Nawaf Talal Salman',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'business',
    studentCode: '119441',
  },
  {
    id: '20',
    name: 'Yasmine Yousef Karim',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'business',
    studentCode: '120368',
  },
  {
    id: '21',
    name: 'Walid Wadih Tahan',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'business',
    studentCode: '121413',
  },
  {
    id: '22',
    name: 'Majid Adil Taha',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'business',
    studentCode: '122401',
  },
  {
    id: '23',
    name: 'Hani Hisham Nasser',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'business',
    studentCode: '123872',
  },
  {
    id: '24',
    name: 'Osama Amjad Barakat',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'business',
    studentCode: '124889',
  },
  {
    id: '25',
    name: 'Haider Mahmoud Suleiman',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 1,
    department: 'business',
    studentCode: '125484',
  },
  {
    id: '26',
    name: 'Zuhair Amjad Mansour',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'computer assembly',
    studentCode: '226555',
  },
  {
    id: '27',
    name: 'Mazin Adil Sarraf',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'computer assembly',
    studentCode: '227596',
  },
  {
    id: '28',
    name: 'Eman Hisham Habib',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'computer assembly',
    studentCode: '228765',
  },
  {
    id: '29',
    name: 'Yusuf Anwar Nasrallah',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'computer assembly',
    studentCode: '229146',
  },
  {
    id: '30',
    name: 'Ziad Karim Jaber',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'computer assembly',
    studentCode: '230983',
  },
  {
    id: '31',
    name: 'Kamal Nabil Suleiman',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'computer assembly',
    studentCode: '231909',
  },
  {
    id: '32',
    name: 'Amr Hisham Obeid',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'computer assembly',
    studentCode: '232828',
  },
  {
    id: '33',
    name: 'Hamza Khalid Kassab',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'computer assembly',
    studentCode: '233361',
  },
  {
    id: '34',
    name: 'Fadel Bassel Hassan',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'computer assembly',
    studentCode: '234880',
  },
  {
    id: '35',
    name: 'Aisha Naji Khoury',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'computer assembly',
    studentCode: '235810',
  },
  {
    id: '36',
    name: 'Sara Talal Sarraf',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'computer assembly',
    studentCode: '236122',
  },
  {
    id: '37',
    name: 'Salim Khalid Habib',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'business',
    studentCode: '237400',
  },
  {
    id: '38',
    name: 'Zaki Fares Rahal',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'business',
    studentCode: '238435',
  },
  {
    id: '39',
    name: 'Abdullah Sami Marzouk',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'business',
    studentCode: '239229',
  },
  {
    id: '40',
    name: 'Dina Naji Nasser',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'business',
    studentCode: '240258',
  },
  {
    id: '41',
    name: 'Hussein Anwar Haidar',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'business',
    studentCode: '241513',
  },
  {
    id: '42',
    name: 'Ghassan Amjad Haidar',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 2,
    department: 'business',
    studentCode: '242103',
  },
  {
    id: '43',
    name: 'Ghada Zahir Kassab',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '343842',
  },
  {
    id: '44',
    name: 'Diyaa Nabil Kanaan',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '344792',
  },
  {
    id: '45',
    name: 'Ahmed Mahmoud Habib',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '345443',
  },
  {
    id: '46',
    name: 'Taim Naji Zayd',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '346134',
  },
  {
    id: '47',
    name: 'Tariq Adil Mahfouz',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '347273',
  },
  {
    id: '48',
    name: 'Suha Mahmoud Awad',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '348834',
  },
  {
    id: '49',
    name: 'Khalid Fouad Kassab',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '349942',
  },
  {
    id: '50',
    name: 'Anas Hisham Wahba',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '350958',
  },
  {
    id: '51',
    name: 'Fatima Riyad Suleiman',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '351794',
  },
  {
    id: '52',
    name: 'Raed Naji Amin',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '352647',
  },
  {
    id: '53',
    name: 'Mahmoud Fares Al-Khatib',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '353915',
  },
  {
    id: '54',
    name: 'Manar Karim Ibrahim',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '354528',
  },
  {
    id: '55',
    name: 'Mariam Wadih Shami',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '355671',
  },
  {
    id: '56',
    name: 'Widad Jamal Ibrahim',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '356447',
  },
  {
    id: '57',
    name: 'Roaa Anwar Sarraf',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '357484',
  },
  {
    id: '58',
    name: 'Sana Adil Kassab',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '358304',
  },
  {
    id: '59',
    name: 'Obada Hisham Sarraf',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '359195',
  },
  {
    id: '60',
    name: 'Adnan Talal Shami',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '360829',
  },
  {
    id: '61',
    name: 'Rami Khalid Kassab',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '361229',
  },
  {
    id: '62',
    name: 'Mohammed Riyad Qassem',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '362508',
  },
  {
    id: '63',
    name: 'Mousa Fouad Habib',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '363287',
  },
  {
    id: '64',
    name: 'Baraa Khalid Odeh',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '364574',
  },
  {
    id: '65',
    name: 'Bilal Fares Odeh',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '365933',
  },
  {
    id: '66',
    name: 'Adel Naji Kanaan',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '366549',
  },
  {
    id: '67',
    name: 'Ihab Bassel Haidar',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '367271',
  },
  {
    id: '68',
    name: 'Louai Mahmoud Nasser',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '368562',
  },
  {
    id: '69',
    name: 'Ghaith Khalid Taha',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'business',
    studentCode: '369394',
  },
  {
    id: '70',
    name: 'Reem Naji Amin',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '370681',
  },
  {
    id: '71',
    name: 'Saad Bassel Najjar',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '371734',
  },
  {
    id: '72',
    name: 'Jawad Fouad Awad',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '372132',
  },
  {
    id: '73',
    name: 'Mostafa Wadih Amin',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '373722',
  },
  {
    id: '74',
    name: 'Nadia Anwar Zaidan',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '374485',
  },
  {
    id: '75',
    name: 'Essam Zahir Zaidan',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '375633',
  },
  {
    id: '76',
    name: 'Lina Zahir Shami',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '376810',
  },
  {
    id: '77',
    name: 'Rania Bassel Yousef',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '377531',
  },
  {
    id: '78',
    name: 'Tamara Bassel Kassab',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '378605',
  },
  {
    id: '79',
    name: 'Ali Riyad Yousef',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '379307',
  },
  {
    id: '80',
    name: 'Qasim Bassel Yousef',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '380906',
  },
  {
    id: '81',
    name: 'Naeem Karim Rizk',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '381944',
  },
  {
    id: '82',
    name: 'Aws Mahmoud Mahfouz',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '382883',
  },
  {
    id: '83',
    name: 'Layla Bassel Wahba',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '383214',
  },
  {
    id: '84',
    name: 'Hassan Mahmoud Awad',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '384633',
  },
  {
    id: '85',
    name: 'Omar Khalid Rizk',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '385874',
  },
  {
    id: '86',
    name: 'Nasser Wadih Obeid',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '386269',
  },
  {
    id: '87',
    name: 'Nour Naji Nasrallah',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '387381',
  },
  {
    id: '88',
    name: 'Faisal Fouad Suleiman',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '388736',
  },
  {
    id: '89',
    name: 'Issam Bassel Yousef',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '389469',
  },
  {
    id: '90',
    name: 'Waseem Hisham Amin',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '390587',
  },
  {
    id: '91',
    name: 'Mustafa Jamal Haidar',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '391268',
  },
  {
    id: '92',
    name: 'Bassam Nabil Shami',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '392327',
  },
  {
    id: '93',
    name: 'Wael Riyad Haidar',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '393162',
  },
  {
    id: '94',
    name: 'Mona Jamal Obeid',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '394232',
  },
  {
    id: '95',
    name: 'Shahed Yousef Nasser',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '395428',
  },
  {
    id: '96',
    name: 'Sami Amjad Zahran',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '396231',
  },
  {
    id: '97',
    name: 'Marwan Riyad Rizk',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '397603',
  },
  {
    id: '98',
    name: 'Badr Jamal Ibrahim',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '398885',
  },
  {
    id: '99',
    name: 'Rafiq Amjad Habib',
    academicYear: '2025-2026',
    status: 'ACTIVE',
    level: 3,
    department: 'computer assembly',
    studentCode: '399205',
  },
];
